<br><br><br>

<center><font size="7" color="blue">The MBA 50s</font></center>


<br><br><br><br>

<font size="4">DATA 618 Quant Finance Week3   Preliminary Allocation By Random Assignment</font>

<br><br>

<br>

<pre>

        Run a random number to select a scenario between 1 and 5

</pre>

<br>

In [127]:
import random

random.randint(1,5)

4

<br>

You are a 37-year-old bond trader in a major investment firm. Your investment portfolio, largely holding high return equities is valued today at $6.2 M. You have just read Jamie Dimon's financial hurricane warning and decided to rebalance your portfolio.

<br>

<br>

<br>

In [128]:

portfolio_schema = {'asset_id':int(),         # unique identifier
            'ticker':'',
             'asset_class':'',  
             'sub_asset_class':'', 
             'ir_risk':'', 
             'eco_risk':'', 
             'price':float(),
             'yield':float(),
             'market_value' : float(),
             'allocation' : float()
}


asset_classes= [
     ["US Treasury",  "Fixed", "Y", "N"],
     ["US Corporate Bond",  "Fixed", "Y", "N"],
     ["Large Cap",  "Equity", "N", "Y"],
     ["Mid Cap",  "Equity", "N", "Y"],
     ["Small Cap",  "Equity", "N", "Y"],
     ["Eq Optoins",  "Equity Derivatives", "N", "Y"],
     ["Eq Futures",   "Equity Derivatives", "N", "Y"],
     ["FI Options",   "FI Derivatives", "N", "Y"],
     ["FI Futures",   "FI Derivatives", "N", "Y"],
     ["Cash",   "Money Market", "N", "N"],
     ["CD",   "Money Market", "N", "N"]    
]



portfolio_df = pd.DataFrame(portfolio_schema, index=[])


def add_asset(ticker, asset_class,sub_asset_class, ir_risk, eco_risk, closing_price, closing_yield,  portfolio_df ):
    
    if (len(portfolio_df)==0):
        asset_id=1
    else:
        asset_id=1+portfolio_df['asset_id'].iloc[-1]
        
    return portfolio_df.append(
        {
            'asset_id' : asset_id, 
            'ticker' : ticker, 
            'asset_class' : asset_class, 
            'sub_asset_class' : sub_asset_class,
            'ir_risk' : ir_risk,
            'eco_risk' : eco_risk, 
            'price' : closing_price,
            'yield' : closing_yield,
            'market_value' : 0,
            'allocation' : 0
                    },
        ignore_index = True)  


for x in range(1,2):
    
    for ac in asset_classes:
        asset_ticker=ac[0]+str(x)
        asset_class1=ac[1]
        asset_class2=ac[0]
        ir_risk=ac[2]
        eco_risk=ac[3]
        portfolio_df=add_asset(asset_ticker, asset_class1, asset_class2,   ir_risk, eco_risk,  0, 0 ,portfolio_df)

<br>

These are our asset classes.

<br>

In [129]:
portfolio_df

,asset_id,ticker,asset_class,sub_asset_class,ir_risk,eco_risk,price,yield,market_value,allocation
0,1,US Treasury1,Fixed,US Treasury,Y,N,0.0,0.0,0.0,0.0
1,2,US Corporate Bond1,Fixed,US Corporate Bond,Y,N,0.0,0.0,0.0,0.0
2,3,Large Cap1,Equity,Large Cap,N,Y,0.0,0.0,0.0,0.0
3,4,Mid Cap1,Equity,Mid Cap,N,Y,0.0,0.0,0.0,0.0
4,5,Small Cap1,Equity,Small Cap,N,Y,0.0,0.0,0.0,0.0
5,6,Eq Optoins1,Equity Derivatives,Eq Optoins,N,Y,0.0,0.0,0.0,0.0
6,7,Eq Futures1,Equity Derivatives,Eq Futures,N,Y,0.0,0.0,0.0,0.0
7,8,FI Options1,FI Derivatives,FI Options,N,Y,0.0,0.0,0.0,0.0
8,9,FI Futures1,FI Derivatives,FI Futures,N,Y,0.0,0.0,0.0,0.0
9,10,Cash1,Money Market,Cash,N,N,0.0,0.0,0.0,0.0
10,11,CD1,Money Market,CD,N,N,0.0,0.0,0.0,0.0

<br>

I want to put $1MM ( 16\% of my money ) in US Treasuries. The FED has sold a lot of Bonds to the market recently so they arent too expensive. We may see some modest increase in market value if the Quantitative Tightening continues.

<br>

In [130]:
total_market_value=6200000
portfolio_df.at[0,'market_value']=1000000
portfolio_df.at[0,'allocation']=portfolio_df.at[0,'market_value']/total_market_value

<br>

<pre>
          Ill allocate 1MM to Corporate Bonds. I would put half in Investment Grade and half in High Yield. 
          
          I will spend time researching for high yield opportunity
          
          I know a technology startup that may win a governemnt contract to supply new tech drones to the Ukaine army and if it does its bond price will soar.
</pre>

<br>

In [131]:
portfolio_df.at[1,'market_value']=1000000
portfolio_df.at[1,'allocation']=portfolio_df.at[1,'market_value']/total_market_value

<br>

<pre>
          Ill allocate 300K to Large and Mid Caps. This is very conversative from what I had. I do think Quantitative Tightening effects big caps and now that the pandemic economy (which killed small companies) is ending, I expect smaller companies to grow now. So Ill allocate 1MM to small caps.
         
</pre>

<br>

In [132]:
portfolio_df.at[2,'market_value']=300000
portfolio_df.at[3,'market_value']=300000
portfolio_df.at[4,'market_value']=1000000
portfolio_df.at[2,'allocation']=portfolio_df.at[2,'market_value']/total_market_value
portfolio_df.at[3,'allocation']=portfolio_df.at[3,'market_value']/total_market_value
portfolio_df.at[4,'allocation']=portfolio_df.at[4,'market_value']/total_market_value

<br>

<pre>

Im going to skip the equity options for now. My new allocations are conservative and trying to hedge now seems risky.
Ill put the remaining cash.

</pre>

<br>

In [133]:
remaining=6200000-portfolio_df['market_value'].sum()

portfolio_df.at[9,'market_value']=remaining
portfolio_df.at[9,'allocation']=portfolio_df.at[9,'market_value']/total_market_value

portfolio_df

,asset_id,ticker,asset_class,sub_asset_class,ir_risk,eco_risk,price,yield,market_value,allocation
0,1,US Treasury1,Fixed,US Treasury,Y,N,0.0,0.0,1000000.0,0.161290
1,2,US Corporate Bond1,Fixed,US Corporate Bond,Y,N,0.0,0.0,1000000.0,0.161290
2,3,Large Cap1,Equity,Large Cap,N,Y,0.0,0.0,300000.0,0.048387
3,4,Mid Cap1,Equity,Mid Cap,N,Y,0.0,0.0,300000.0,0.048387
4,5,Small Cap1,Equity,Small Cap,N,Y,0.0,0.0,1000000.0,0.161290
5,6,Eq Optoins1,Equity Derivatives,Eq Optoins,N,Y,0.0,0.0,0.0,0.000000
6,7,Eq Futures1,Equity Derivatives,Eq Futures,N,Y,0.0,0.0,0.0,0.000000
7,8,FI Options1,FI Derivatives,FI Options,N,Y,0.0,0.0,0.0,0.000000
8,9,FI Futures1,FI Derivatives,FI Futures,N,Y,0.0,0.0,0.0,0.000000
9,10,Cash1,Money Market,Cash,N,N,0.0,0.0,2600000.0,0.419355
10,11,CD1,Money Market,CD,N,N,0.0,0.0,0.0,0.000000